"""
Creates a metadata file for the dataset, containing relevant information about the images in the dataset: 
    - Image_id: Unique identifier for each image
    - Filepath: Path to the original image file
    - Source_type: The source of the image - real (wiki), generated by insight, inpainting, text2image
    - Label: Real (1) or Fake (0)
    - Split: The split where the image will belong atfer data spliting
"""

import os
import logging
import pandas as pd
from sklearn.model_selection import train_test_split

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s - %(message)s"
)

## --------- CONFIGURATION ---------
DATA_DIR = 'data'
WIKI_DATA_NAME = 'wiki' # real data
INPAINTING_DATA_NAME = 'inpainting'
INSIGHT_DATA_NAME = 'insight'
TEXT2IMG_DATA_NAME = 'text2img'

NUMBER_SAMPLES = 500

OUTPUT_PATH = 'data/metadata.csv'

source_type_dict = {
        "wiki": WIKI_DATA_NAME,
        "inpainting": INPAINTING_DATA_NAME,
        "insight": INSIGHT_DATA_NAME,
        "text2image": TEXT2IMG_DATA_NAME,
    }



# ----------- Metadata construction ----------
def build_metadata(data_dir: str, source_type_dict: dict) -> pd.DataFrame:
    """
    Creates and returns a metadata dataframe with columns:
        'image_id', 'filepath', 'source_type' and 'label'

    Args: 
        data_dir: directory containing the dataset
        source_type_dict: mapping from metadata source type to folder name
    Return:
        pd.DataFrame
    Raises: 
        FileNotFoundError:
            - If `data_dir` does not exist.
            - If any expected dataset subfolder in `source_type_dict` does not exist.
        ValueError:
            - If no valid `.jpg` image files are found in the dataset folders.   
    """
    # check if the dataset exists
    if not os.path.isdir(data_dir):
        raise FileNotFoundError(f"Dataset Directory {data_dir} Not Found")

    records = []

    for source_type, folder_name in source_type_dict.items():
        # print("source_type", source_type)
        folder_path = os.path.join(data_dir, folder_name)

        if not os.path.isdir(folder_path):
            raise FileNotFoundError(f"Subfolder Dataset Directory {folder_path} Not Found")
        
        logging.info(f"Adding images from {folder_path} subfolder")
    
    
        for root, _, files in os.walk(folder_path):
            files = sorted(files)                     # keeps all files in the same order 
            for fname in files:
                if not fname.lower().endswith(".jpg"):
                    continue

                filepath = os.path.join(root, fname)

                rel_path = os.path.relpath(filepath, data_dir)
                image_id = os.path.splitext(rel_path)[0].replace(os.sep, "_")

                label = 1 if source_type == "wiki" else 0

                records.append({
                    "image_id": image_id,
                    "filepath": filepath,
                    "source_type": source_type,
                    "label": label,
                })

    if len(records) == 0:
        raise ValueError("No images were found. Check DATA_DIR and folder names.")

    metadata_df = pd.DataFrame(records)
    if not metadata_df["filepath"].is_unique:
        logging.warning("Duplicate filepaths found in metadata.")

    return metadata_df


def select_samples(df:pd.DataFrame, number_samples:int) -> pd.DataFrame: # por real/fake
    """
    Selects the first `number_samples` samples per source_type.
    Args:
        df: Metadata dataframe containing a 'source_type' column.
        number_samples: Number of samples to keep per source_type.

    Returns:
        pd.DataFrame: Filtered dataframe.

    Raises:
        ValueError:
            - If any source_type has fewer samples than number_samples.
    """
    counts = df["source_type"].value_counts()
    if (counts < number_samples).any():
        raise ValueError(f"Subfolders only have 30000 images. Please lower NUMBER_SAMPLES to <=30000")

    # keep top N per source_type
    df_selected = (
        df.groupby("source_type", group_keys=False)
          .head(number_samples)
    )
    return df_selected


def split_data(df: pd.DataFrame, test_size: float) -> pd.DataFrame:
    """
    Assigns a split to every image by adding a column 'split' to the metadata dataframe.
    The split is stratified by 'source_type' so that the distribution of:
        - wiki
        - inpainting
        - insight
        - text2image
    is approximately preserved across train and test sets.

    Args:
        df: the metadata dataframe returned by `build_metadata`
        test_size: proportion of the test
    
    Returns:
        pd.DataFrame: the dataframe with 'split' column added

    Raises:
        ValueError:
            - If `source_type` does not exist
            - If the stratified split fails
    """
    if "source_type" not in df.columns:
        raise ValueError("Dataframe must contain 'source_type' column.")
    df = df.copy()
    try:
        _, test_idx = train_test_split(
            df.index,
            test_size=test_size,
            stratify=df["source_type"],
            random_state=42
        )
        df["split"] = "train"
        df.loc[test_idx, "split"] = "test"
    
    except Exception as e:
            raise ValueError("Stratified split failed. Make sure each source_type has enough samples.") from e
    return df


def save_metadata(df: pd.DataFrame, output_path: str) -> None:
    """
    Saves the metadata dataframe in `output_path` (csv)
    Args:
        df: metadata dataframe to save.
        output_path: data/metadata.csv

    Raises:
        ValueError:
            - If the dataframe is empty.
    """
    if df.empty:
        raise ValueError("Metadata Dataframe is empty")
    df.to_csv(output_path, index=False)
    logging.info(f"Metadata saved to: {output_path}")


# --------- main --------

def main():
    return
df = build_metadata(data_dir=DATA_DIR, source_type_dict=source_type_dict)
df = select_samples(df=df, number_samples=NUMBER_SAMPLES)
df_split = split_data(df=df, test_size=0.2)
print(df_split.tail())