"""
Creates a metadata file for the dataset, containing relevant information about the images in the dataset: 
    - Image_id: Unique identifier for each image
    - Filepath: Path to the original image file
    - Source_type: The source of the image - real (wiki), generated by insight, inpainting, text2image
    - Label: Real (1) or Fake (0)
    - Split: The split where the image will belong atfer data spliting
"""

import os
import logging
import pandas as pd
from sklearn.model_selection import train_test_split

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s - %(message)s"
)

## --------- CONFIGURATION ---------
DATA_DIR = 'data'
WIKI_DATA_NAME = 'wiki' # real data
INPAINTING_DATA_NAME = 'inpainting'
INSIGHT_DATA_NAME = 'insight'
TEXT2IMG_DATA_NAME = 'text2img'

NUMBER_SAMPLES = 20

OUTPUT_PATH = 'data/metadata.csv'

source_type_dict = {
        "wiki": WIKI_DATA_NAME,
        "inpainting": INPAINTING_DATA_NAME,
        "insight": INSIGHT_DATA_NAME,
        "text2image": TEXT2IMG_DATA_NAME,
    }



# ----------- Metadata construction ----------
def build_metadata(data_dir: str, source_type_dict: dict, ) -> pd.DataFrame:
    """
    Creates and returns a metadata dataframe with columns:
        'image_id', 'filepath', 'source_type' and 'label'

    Args: 
        data_dir: directory containing the dataset
        source_type_dict: mapping from metadata source type to folder name
    Return:
        pd.DataFrame
    Raises: 
        FileNotFoundError:
            - If `data_dir` does not exist.
            - If any expected dataset subfolder in `source_type_dict` does not exist.
        ValueError:
            - If no valid `.jpg` image files are found in the dataset folders.   
    """
    # check if the dataset exists
    if not os.path.isdir(data_dir):
        raise FileNotFoundError(f"Dataset Directory {data_dir} Not Found")

    records = []

    for source_type, folder_name in source_type_dict.items():
        # print("source_type", source_type)
        folder_path = os.path.join(data_dir, folder_name)

        if not os.path.isdir(folder_path):
            raise FileNotFoundError(f"Subfolder Dataset Directory {folder_path} Not Found")
        
        logging.info(f"Adding images from {folder_path} subfolder")
    
    
        for root, _, files in os.walk(folder_path):
            files = sorted(files)                     # keeps all files in the same order 
            for fname in files:
                if not fname.lower().endswith(".jpg"):
                    continue

                filepath = os.path.join(root, fname)

                rel_path = os.path.relpath(filepath, data_dir)
                image_id = os.path.splitext(rel_path)[0].replace(os.sep, "_")

                label = 1 if source_type == "wiki" else 0

                records.append({
                    "image_id": image_id,
                    "filepath": filepath,
                    "source_type": source_type,
                    "label": label,
                })

    if len(records) == 0:
        raise ValueError("No images were found. Check DATA_DIR and folder names.")

    metadata_df = pd.DataFrame(records)
    if not metadata_df["filepath"].is_unique:
        logging.warning("Duplicate filepaths found in metadata.")

    return metadata_df


def select_samples(df:pd.DataFrame, number_samples:int) -> pd.DataFrame: # por real/fake
    """
    Selects the first `number_samples` samples per source_type.
    Args:
        df: Metadata dataframe containing a 'source_type' column.
        number_samples: Number of samples to keep per source_type.

    Returns:
        pd.DataFrame: Filtered dataframe.

    Raises:
        ValueError:
            - If any source_type has fewer samples than number_samples.
    """
    counts = df["source_type"].value_counts()
    if (counts < number_samples).any():
        raise ValueError(f"Subfolders only have 30000 images. Please lower NUMBER_SAMPLES to <=30000")

    # keep top N per source_type
    df_selected = (
        df.groupby("source_type", group_keys=False)
          .head(number_samples)
    )
    return df_selected


def split_data(df: pd.DataFrame, train_size: float = 0.7, val_size: float = 0.15) -> pd.DataFrame:
    """
    Atribui splits (train, val, test) de forma estratificada por 'source_type'.
    Segue a proporção 70/15/15 definida no plano.
    """
    if "source_type" not in df.columns:
        raise ValueError("O DataFrame precisa da coluna 'source_type' para estratificar.")
    
    df = df.copy()
    
    # 1. Primeiro corte: Separar o Treino (70%) do resto (30%)
    train_idx, temp_idx = train_test_split(
        df.index,
        train_size=train_size,
        stratify=df["source_type"],
        random_state=42
    )
    
    # 2. Segundo corte: Dividir os 30% restantes a meio (15% val, 15% test)
    # 0.5 de 30% = 15% do total
    val_idx, test_idx = train_test_split(
        temp_idx,
        train_size=0.5, 
        stratify=df.loc[temp_idx, "source_type"],
        random_state=42
    )
    
    df["split"] = ""
    df.loc[train_idx, "split"] = "train"
    df.loc[val_idx, "split"] = "val"
    df.loc[test_idx, "split"] = "test"
    
    return df

def save_metadata(df: pd.DataFrame, output_path: str) -> None:
    """
    Saves the metadata dataframe in `output_path` (csv)
    Args:
        df: metadata dataframe to save.
        output_path: data/metadata.csv

    Raises:
        ValueError:
            - If the dataframe is empty.
    """
    if df.empty:
        raise ValueError("Metadata Dataframe is empty")
    df.to_csv(output_path, index=False)
    logging.info(f"Metadata saved to: {output_path}")


# --------- main --------
if __name__ == "__main__":
    # Carrega e filtra os dados
    df = build_metadata(data_dir=DATA_DIR, source_type_dict=source_type_dict)
    df = select_samples(df=df, number_samples=NUMBER_SAMPLES)
    
    # Aplica a divisão tripla (70/15/15)
    df_split = split_data(df, train_size=0.7, val_size=0.15)
    
    # Guarda os resultados
    save_metadata(df_split, OUTPUT_PATH)
    
    # Verificação rápida no terminal
    print("\nResumo dos Splits por Fonte:")
    print(pd.crosstab(df_split['source_type'], df_split['split']))